# Example: Redis cache infrastructure service
# Demonstrates infrastructure-tier spell configuration

name: redis

image:
  name: redis
  tag: 7.2-alpine
  pullPolicy: IfNotPresent

replicas: 1

# Redis default port
ports:
  - name: redis
    containerPort: 6379
    protocol: TCP

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis

# Redis-specific configuration
command:
  - redis-server
  - --appendonly
  - "yes"
  - --requirepass
  - "$(REDIS_PASSWORD)"

# Environment variables
env:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-credentials
        key: password

# Persistent storage
persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /data

# Resource limits for infrastructure services
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Health checks
livenessProbe:
  enabled: true
  exec:
    command:
      - redis-cli
      - ping
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  exec:
    command:
      - redis-cli
      - ping
  initialDelaySeconds: 5
  periodSeconds: 5

# Optional: Vault integration for Redis password
# vault:
#   redis-credentials:
#     path: secret/data/infrastructure/redis
#     outputType: secret
#     keys:
#       - password
